spring.application.name=pawmaru-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pawmaru}
spring.datasource.username=${DB_USERNAME:pawmaru}
spring.datasource.password=${DB_PASSWORD:pawmaru-local}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
management.endpoints.web.exposure.include=health,info
server.forward-headers-strategy=framework
